version: "3"
services:
  imagick_php_backend:
    build: docker/php_backend
    image: imagick_php_backend:latest
    volumes:
      - .:/var/app
    restart: always
  imagick_php_backend_debug:
    build: docker/php_backend_debug
    image: imagick_php_backend_debug:latest
    depends_on:
      - imagick_php_backend
    volumes:
      - .:/var/app
    restart: always
  imagick_php_base:
    build: docker/imagick_php_base
    image: imagick_php_base:latest
    command: ["tail", "-f", "/var/app/docker/imagick_php_base/README.md"]
    volumes:
      - .:/var/app
  js_dev_builder:
    build: docker/js_dev_builder
    volumes:
      - .:/var/app
#  sass_dev_builder:
#    build: containers/sass_dev_builder
#    volumes:
#      - .:/var/app
  installer:
    build: docker/installer
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - .:/var/app
#  npm:
#    build: docker/npm
#    #environment:
#    #  - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#    #  - COMPOSER_ALLOW_SUPERUSER=1
#    #labels:
#    #  com.datadoghq.ad.logs: '[{"source": "php", "service": "phpimagick_installer"}]'
#    ports:
#      - 8888:8888
#    volumes:
#      - .:/var/app
  redis:
    image: redis:4.0.6
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "phpimagick_redis"}]'
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
  web_server:
    build: docker/web_server
    image: imagick_web_server:latest
    command: ["/usr/sbin/nginx", "-c", "/etc/config/nginx.conf"]
    depends_on:
      - imagick_php_backend
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "phpimagick_nginx"}]'
    volumes:
      - .:/var/app
      - ./docker/web_server/config:/etc/config
    restart: always
  workers:
    build: docker/background_worker
    image: imagick_php_worker:latest
    depends_on:
      - redis
      - imagick_php_backend
    labels:
      com.datadoghq.ad.logs: '[{"source": "php", "service": "phpimagick_supervisord"}]'
    volumes:
      - .:/var/app
    restart: always